name: "zexon-zadanie"
services:
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: "zexon-zadanie_php"
    volumes:
      - ./:/var/www/html
    networks:
      - shared_network
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: "zexon-zadanie_nginx"
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
    networks:
      - shared_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zexon_zadanie.rule=Host(`zexon.localhost`)"
      - "traefik.http.routers.zexon_zadanie.entrypoints=web"
      - "traefik.http.services.zexon_zadanie.loadbalancer.server.port=80"
networks:
  shared_network:
    external: true
